# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: sarthaknimje@gmail.com
author_name: Sarthak Nimje
contract_name: manage
deployment_language: python
preset_name: production
project_name: manager-contracts

